const express = require("express");
const cors = require("cors");
const client = require("./db");
//const pg = require('pg');

const app = express();

// middleware
app.use(cors());
app.use(express.json()); //req.body

// CONNECT TO POSTGRESQL DATABASE
client.connect(function (err) {
  if (err) {
    return console.error("could not connect to postgres", err);
  }
  client.query('SELECT NOW() AS "theTime"', function (err, result) {
    if (err) {
      return console.error("error running query", err);
    }
    console.log("connected to database");
  });
});


//------ROUTES-------//

// POST REVIEWS
app.post("/reviews", (req, res) => {
  const id = Math.floor(Math.random() * 1000000); // id generated by backend rather than frontend
  const { student_id, review, course_id, likes, dislikes, difficulty, workload, teaching } = req.body;
  client.query(
    "INSERT INTO reviews (id, student_id, review, course_id, likes, dislikes, difficulty, workload, teaching) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",
    [id, student_id, review, course_id, likes, dislikes, difficulty, workload, teaching],
    (err, result) => {
      if (!err) {
        res.json(result.rows[0]);
        console.log("Successfully added data");
      } else {
        console.log(err.message);
      }
      client.end;
    }
  );
});

// GET REVIEWS
app.get("/reviews", (req, res) => {
  client.query("SELECT * FROM reviews", (err, result) => {
    if (!err) {
      const resultRows = result.rows;
      res.json(resultRows);
      console.log("Successfully fetched data");
    } else {
      console.log(err.message);
    }
    client.end;
  });
});

// GET SPECIFIC COURSE REVIEWS
app.get("/reviews/:id", (req, res) => {
  const { id } = req.params;
  client.query(
    "SELECT * FROM reviews WHERE course_id = $1",
    [id],
    (err, result) => {
      if (!err) {
        res.json(result.rows);
        console.log("Successfully fetched data");
      } else {
        console.log(err.message);
      }
      client.end;
    }
  );
});

// UPDATE REVIEW
app.put("/reviews/:id", (req, res) => {
  const { id } = req.params;
  const { likes } = req.body;
  const { dislikes } = req.body;
  client.query(
    "UPDATE reviews SET likes=$1, dislikes=$2 WHERE id=$3",
    [likes, dislikes, id],
    (err, response) => {
      if (!err) {
        res.json("Review was updated");
        console.log("Successfully updated review");
      } else {
        console.log(err.message);
      }
    }
  );
});

// DELETE REVIEW
app.delete("/reviews/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const deleteReview = await client.query(
      "DELETE FROM reviews WHERE id = $1",
      [id],
      (err, response) => {
        if (!err) {
          res.json("Review was deleted");
          console.log("Successfully deleted review");
        } else {
          console.log(err.message);
        }
        client.end;
      }
    );
  } catch (err) {
    console.log(err.message);
  }
});



//------STUDENTS TABLE ROUTES-------//

app.get("/students", (req, res) => {
  client.query("SELECT * FROM students", (err, result) => {
    if (!err) {
      const resultRows = result.rows;
      res.json(resultRows);
      console.log("Successfully fetched data");
    } else {
      console.log(err.message);
    }
    client.end;
  });
});


const PORT = 3001;
app.listen(PORT, () => {
  console.log(`server has started on port ${PORT}`);
});
